### PR TITLE
Allow for multiple arguments

### PR DESCRIPTION
**Pull request by litscher**
Fix for #5 
Changed others to args 
Added a dockerfile + entrypoint.sh which allows for any valid argument to be passed through. [[more info](https://docs.github.com/en/actions/creating-actions/dockerfile-support-for-github-actions#entrypoint)]

### CODE REVIEW

**Comment by javixeneize** [comment]
The only change needed is in the action.yml, none of the other changes are needed

Thanks

**Comment by litscher** [comment]
The other changes are needed because that is how we can manipulate the arguments and allow them to function properly without writing them all out. 
And if we write them all out, this will fail because not all of the arguments have defaults or should be part of the argument everytime.

**Comment by litscher** [comment]
going to close this until I have something working properly.

**Comment by javixeneize** [comment]
No, what i mean is that just with the yml it will work, the other files are not needed. Redo the PR only with the yml and get rid of the other files :)

**Comment by litscher** [comment]
I was not able to get it to function with just the YAML because the arguments needed to be modified due to how they are consumed. If you can, I would truly appreciate it if you shared how.

**Pull request closed without merging**
